language: android
android:
  components:
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.3

    # The SDK version used to compile your project
    - android-25

    # Additional components
    - extra-android-m2repository
    - extra-google-m2repository

jdk: oraclejdk8

script: ./gradlew clean assembleDebug
